spring:
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer-service
                fallbackuri: forward:/customerFallBack
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: order-service
                fallbackuri: forward:/orderFallBack
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: product-service
                fallbackuri: forward:/productFallBack

server:
  port: 9000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    web:
      exposure:
        include: hystrix.stream

resilience4j:
  circuitbreaker:
    instances:
      sampahService:
        slidingWindowSize: 10                     #unit request
        permittedNumberOfCallsInHalfOpenState: 5  #unit request
        failureRateThreshold: 50                  #percent
        waitDurationInOpenState: 5000            #10 seconds
        registerHealthIndicator: true